/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
import * as reactQuery from "@tanstack/react-query";
import { useApiContext, ApiContext, queryKeyFn } from "./apiContext";
import { deepMerge } from "./apiUtils";
import type * as Fetcher from "./apiFetcher";
import { apiFetch } from "./apiFetcher";
import type * as Schemas from "./apiSchemas";

type QueryFnOptions = {
  signal?: AbortController["signal"];
};

export type UpsertZoningTypesError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.ErrorResponse;
    }
  | {
      status: 404;
      payload: Schemas.ErrorResponse;
    }
  | {
      status: 500;
      payload: Schemas.ErrorResponse;
    }
>;

export type UpsertZoningTypesResponse = Schemas.ZoningType[];

export type UpsertZoningTypesVariables = {
  body: Schemas.ZoningUpdateRequest;
} & ApiContext["fetcherOptions"];

export const fetchUpsertZoningTypes = (
  variables: UpsertZoningTypesVariables,
  signal?: AbortSignal,
) =>
  apiFetch<
    UpsertZoningTypesResponse,
    UpsertZoningTypesError,
    Schemas.ZoningUpdateRequest,
    {},
    {},
    {}
  >({ url: "/api/properties/zoning", method: "put", ...variables, signal });

export const useUpsertZoningTypes = (
  options?: Omit<
    reactQuery.UseMutationOptions<
      UpsertZoningTypesResponse,
      UpsertZoningTypesError,
      UpsertZoningTypesVariables
    >,
    "mutationFn"
  >,
) => {
  const { fetcherOptions } = useApiContext();
  return reactQuery.useMutation<
    UpsertZoningTypesResponse,
    UpsertZoningTypesError,
    UpsertZoningTypesVariables
  >({
    mutationFn: (variables: UpsertZoningTypesVariables) =>
      fetchUpsertZoningTypes(deepMerge(fetcherOptions, variables)),
    ...options,
  });
};

export type GetPropertiesInBoundingBoxQueryParams = {
  /**
   * @format double
   */
  west: number;
  /**
   * @format double
   */
  south: number;
  /**
   * @format double
   */
  east: number;
  /**
   * @format double
   */
  north: number;
};

export type GetPropertiesInBoundingBoxError = Fetcher.ErrorWrapper<
  | {
      status: 400;
      payload: Schemas.ErrorResponse;
    }
  | {
      status: 500;
      payload: Schemas.ErrorResponse;
    }
>;

export type GetPropertiesInBoundingBoxResponse = Schemas.Property[];

export type GetPropertiesInBoundingBoxVariables = {
  queryParams: GetPropertiesInBoundingBoxQueryParams;
} & ApiContext["fetcherOptions"];

export const fetchGetPropertiesInBoundingBox = (
  variables: GetPropertiesInBoundingBoxVariables,
  signal?: AbortSignal,
) =>
  apiFetch<
    GetPropertiesInBoundingBoxResponse,
    GetPropertiesInBoundingBoxError,
    undefined,
    {},
    GetPropertiesInBoundingBoxQueryParams,
    {}
  >({ url: "/api/properties", method: "get", ...variables, signal });

export function getPropertiesInBoundingBoxQuery(
  variables: GetPropertiesInBoundingBoxVariables,
): {
  queryKey: reactQuery.QueryKey;
  queryFn: (
    options: QueryFnOptions,
  ) => Promise<GetPropertiesInBoundingBoxResponse>;
};

export function getPropertiesInBoundingBoxQuery(
  variables: GetPropertiesInBoundingBoxVariables | reactQuery.SkipToken,
): {
  queryKey: reactQuery.QueryKey;
  queryFn:
    | ((options: QueryFnOptions) => Promise<GetPropertiesInBoundingBoxResponse>)
    | reactQuery.SkipToken;
};

export function getPropertiesInBoundingBoxQuery(
  variables: GetPropertiesInBoundingBoxVariables | reactQuery.SkipToken,
) {
  return {
    queryKey: queryKeyFn({
      path: "/api/properties",
      operationId: "getPropertiesInBoundingBox",
      variables,
    }),
    queryFn:
      variables === reactQuery.skipToken
        ? reactQuery.skipToken
        : ({ signal }: QueryFnOptions) =>
            fetchGetPropertiesInBoundingBox(variables, signal),
  };
}

export const useSuspenseGetPropertiesInBoundingBox = <
  TData = GetPropertiesInBoundingBoxResponse,
>(
  variables: GetPropertiesInBoundingBoxVariables,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesInBoundingBoxResponse,
      GetPropertiesInBoundingBoxError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useApiContext(options);
  return reactQuery.useSuspenseQuery<
    GetPropertiesInBoundingBoxResponse,
    GetPropertiesInBoundingBoxError,
    TData
  >({
    ...getPropertiesInBoundingBoxQuery(deepMerge(fetcherOptions, variables)),
    ...options,
    ...queryOptions,
  });
};

export const useGetPropertiesInBoundingBox = <
  TData = GetPropertiesInBoundingBoxResponse,
>(
  variables: GetPropertiesInBoundingBoxVariables | reactQuery.SkipToken,
  options?: Omit<
    reactQuery.UseQueryOptions<
      GetPropertiesInBoundingBoxResponse,
      GetPropertiesInBoundingBoxError,
      TData
    >,
    "queryKey" | "queryFn" | "initialData"
  >,
) => {
  const { queryOptions, fetcherOptions } = useApiContext(options);
  return reactQuery.useQuery<
    GetPropertiesInBoundingBoxResponse,
    GetPropertiesInBoundingBoxError,
    TData
  >({
    ...getPropertiesInBoundingBoxQuery(
      variables === reactQuery.skipToken
        ? variables
        : deepMerge(fetcherOptions, variables),
    ),
    ...options,
    ...queryOptions,
  });
};

export type QueryOperation = {
  path: "/api/properties";
  operationId: "getPropertiesInBoundingBox";
  variables: GetPropertiesInBoundingBoxVariables | reactQuery.SkipToken;
};
