/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type ZoningUpdateRequest = {
  propertyIds: number[];
  zoningType: "Residential" | "Commercial" | "Industrial";
};

export type ZoningType = {
  /**
   * @format int64
   */
  propertyRefId?: number;
  zoningType?: "Residential" | "Commercial" | "Industrial";
  /**
   * @format date-time
   */
  updatedAt?: string;
};

export type Coordinate = {
  /**
   * @format double
   */
  x?: number;
  /**
   * @format double
   */
  y?: number;
  /**
   * @format double
   */
  z?: number;
  coordinate?: Coordinate;
  /**
   * @format double
   */
  m?: number;
};

export type CoordinateSequence = {
  /**
   * @format int32
   */
  dimension?: number;
  /**
   * @format int32
   */
  measures?: number;
};

export type CoordinateSequenceFactory = Record<string, any>;

export type Envelope = {
  /**
   * @format double
   */
  minX?: number;
  /**
   * @format double
   */
  maxX?: number;
  /**
   * @format double
   */
  minY?: number;
  /**
   * @format double
   */
  maxY?: number;
  /**
   * @format double
   */
  area?: number;
  /**
   * @format double
   */
  width?: number;
  /**
   * @format double
   */
  height?: number;
  /**
   * @format double
   */
  diameter?: number;
  ["null"]?: boolean;
};

export type Geometry = {
  envelope?: Geometry;
  factory?: GeometryFactory;
  userData?: Record<string, any>;
  simple?: boolean;
  /**
   * @format int32
   */
  srid?: number;
  precisionModel?: PrecisionModel;
  coordinate?: Coordinate;
  coordinates?: Coordinate[];
  /**
   * @format int32
   */
  numPoints?: number;
  rectangle?: boolean;
  /**
   * @format double
   */
  area?: number;
  centroid?: Point;
  interiorPoint?: Point;
  boundary?: Geometry;
  /**
   * @format int32
   */
  boundaryDimension?: number;
  envelopeInternal?: Envelope;
  geometryType?: string;
  /**
   * @format int32
   */
  dimension?: number;
  /**
   * @format int32
   */
  numGeometries?: number;
  /**
   * @format double
   */
  length?: number;
  empty?: boolean;
  valid?: boolean;
};

export type GeometryFactory = {
  precisionModel?: PrecisionModel;
  coordinateSequenceFactory?: CoordinateSequenceFactory;
  /**
   * @format int32
   */
  srid?: number;
};

export type LinearRing = {
  envelope?: Geometry;
  factory?: GeometryFactory;
  userData?: Record<string, any>;
  /**
   * @format int32
   */
  boundaryDimension?: number;
  geometryType?: string;
  closed?: boolean;
  coordinateSequence?: CoordinateSequence;
  startPoint?: Point;
  endPoint?: Point;
  ring?: boolean;
  coordinate?: Coordinate;
  coordinates?: Coordinate[];
  /**
   * @format int32
   */
  numPoints?: number;
  boundary?: Geometry;
  /**
   * @format int32
   */
  dimension?: number;
  /**
   * @format double
   */
  length?: number;
  empty?: boolean;
  simple?: boolean;
  /**
   * @format int32
   */
  srid?: number;
  precisionModel?: PrecisionModel;
  rectangle?: boolean;
  /**
   * @format double
   */
  area?: number;
  centroid?: Point;
  interiorPoint?: Point;
  envelopeInternal?: Envelope;
  /**
   * @format int32
   */
  numGeometries?: number;
  valid?: boolean;
};

export type Point = {
  envelope?: Geometry;
  factory?: GeometryFactory;
  userData?: Record<string, any>;
  coordinates?: Coordinate[];
  simple?: boolean;
  /**
   * @format double
   */
  x?: number;
  /**
   * @format double
   */
  y?: number;
  coordinateSequence?: CoordinateSequence;
  coordinate?: Coordinate;
  /**
   * @format int32
   */
  numPoints?: number;
  boundary?: Geometry;
  /**
   * @format int32
   */
  boundaryDimension?: number;
  geometryType?: string;
  /**
   * @format int32
   */
  dimension?: number;
  empty?: boolean;
  /**
   * @format int32
   */
  srid?: number;
  precisionModel?: PrecisionModel;
  rectangle?: boolean;
  /**
   * @format double
   */
  area?: number;
  centroid?: Point;
  interiorPoint?: Point;
  envelopeInternal?: Envelope;
  /**
   * @format int32
   */
  numGeometries?: number;
  /**
   * @format double
   */
  length?: number;
  valid?: boolean;
};

export type Polygon = {
  envelope?: Geometry;
  factory?: GeometryFactory;
  userData?: Record<string, any>;
  exteriorRing?: LinearRing;
  /**
   * @format int32
   */
  numInteriorRing?: number;
  coordinate?: Coordinate;
  coordinates?: Coordinate[];
  /**
   * @format int32
   */
  numPoints?: number;
  rectangle?: boolean;
  /**
   * @format double
   */
  area?: number;
  boundary?: Geometry;
  /**
   * @format int32
   */
  boundaryDimension?: number;
  geometryType?: string;
  /**
   * @format int32
   */
  dimension?: number;
  /**
   * @format double
   */
  length?: number;
  empty?: boolean;
  simple?: boolean;
  /**
   * @format int32
   */
  srid?: number;
  precisionModel?: PrecisionModel;
  centroid?: Point;
  interiorPoint?: Point;
  envelopeInternal?: Envelope;
  /**
   * @format int32
   */
  numGeometries?: number;
  valid?: boolean;
};

export type PrecisionModel = {
  /**
   * @format double
   */
  scale?: number;
  /**
   * @format int32
   */
  maximumSignificantDigits?: number;
  /**
   * @format double
   */
  offsetX?: number;
  /**
   * @format double
   */
  offsetY?: number;
  type?: Type;
  floating?: boolean;
};

export type Property = {
  /**
   * @format int64
   */
  id: number;
  geom: Polygon;
  name: string;
  mailCity?: string;
  mailZip?: string;
  mailadd?: string;
  parcelNumber: string;
  path: string;
  useDescription: string;
  zoningSub: string;
  zoningType: "Residential" | "Commercial" | "Industrial";
};

export type Type = Record<string, any>;
