/**
 * Generated by @openapi-codegen
 *
 * @version v0
 */
export type GeoJsonPolygon = {
  /**
   * @example Polygon
   */
  type?: string;
  coordinates?: number[][][];
};

export type ZoningUpdateRequest = {
  propertyIds: number[];
  zoningType: "Residential" | "Commercial" | "Industrial" | "Planned";
};

export type ErrorResponse = {
  /**
   * @format int32
   */
  status?: number;
  message?: string;
  /**
   * @format date-time
   */
  timestamp?: string;
  errors?: {
    [key: string]: string;
  };
};

export type ZoningType = {
  /**
   * @format int64
   */
  propertyRefId?: number;
  zoningType?: "Residential" | "Commercial" | "Industrial" | "Planned";
  /**
   * @format date-time
   */
  updatedAt?: string;
};

export type Property = {
  /**
   * @format int64
   */
  id: number;
  geom: GeoJsonPolygon;
  name: string;
  mailCity?: string;
  mailZip?: string;
  mailadd?: string;
  parcelNumber: string;
  path: string;
  useDescription: string;
  zoningSub: string;
  zoningType: "Residential" | "Commercial" | "Industrial" | "Planned";
};
